In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
import datasets 
print(datasets.__version__)

3.6.0

In [4]:
import socket

print(socket.getaddrinfo("huggingface.co", 443))

[(<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:4e00:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:7600:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:c800:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:d000:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:9800:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:8c00:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:b400:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2600:9000:213c:8e00:17:b174:6d00:93a1', 443, 0, 0)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('99.86.30.118', 443)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('99.86.30.112', 443)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('99.86.30.69', 443)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('99.86.30.85', 443))]

In [3]:
from datasets import load_dataset

dataset = load_dataset(
    "PolyAI/banking77",
    trust_remote_code=True
)

dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 10003
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 3080
    })
})

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 10003
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 3080
    })
})

In [5]:
dataset["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 10003
})

In [6]:
dataset["train"][0]

{'text': 'I am still waiting on my card?', 'label': 11}

In [7]:
dataset["train"][1]

{'text': "What can I do if my card still hasn't arrived after 2 weeks?",
 'label': 11}

In [8]:
dataset["train"].features

{'text': Value(dtype='string', id=None),
 'label': ClassLabel(names=['activate_my_card', 'age_limit', 'apple_pay_or_google_pay', 'atm_support', 'automatic_top_up', 'balance_not_updated_after_bank_transfer', 'balance_not_updated_after_cheque_or_cash_deposit', 'beneficiary_not_allowed', 'cancel_transfer', 'card_about_to_expire', 'card_acceptance', 'card_arrival', 'card_delivery_estimate', 'card_linking', 'card_not_working', 'card_payment_fee_charged', 'card_payment_not_recognised', 'card_payment_wrong_exchange_rate', 'card_swallowed', 'cash_withdrawal_charge', 'cash_withdrawal_not_recognised', 'change_pin', 'compromised_card', 'contactless_not_working', 'country_support', 'declined_card_payment', 'declined_cash_withdrawal', 'declined_transfer', 'direct_debit_payment_not_recognised', 'disposable_card_limits', 'edit_personal_details', 'exchange_charge', 'exchange_rate', 'exchange_via_app', 'extra_charge_on_statement', 'failed_transfer', 'fiat_currency_support', 'get_disposable_virtual_card', 'get_physical_card', 'getting_spare_card', 'getting_virtual_card', 'lost_or_stolen_card', 'lost_or_stolen_phone', 'order_physical_card', 'passcode_forgotten', 'pending_card_payment', 'pending_cash_withdrawal', 'pending_top_up', 'pending_transfer', 'pin_blocked', 'receiving_money', 'Refund_not_showing_up', 'request_refund', 'reverted_card_payment?', 'supported_cards_and_currencies', 'terminate_account', 'top_up_by_bank_transfer_charge', 'top_up_by_card_charge', 'top_up_by_cash_or_cheque', 'top_up_failed', 'top_up_limits', 'top_up_reverted', 'topping_up_by_card', 'transaction_charged_twice', 'transfer_fee_charged', 'transfer_into_account', 'transfer_not_received_by_recipient', 'transfer_timing', 'unable_to_verify_identity', 'verify_my_identity', 'verify_source_of_funds', 'verify_top_up', 'virtual_card_not_working', 'visa_or_mastercard', 'why_verify_identity', 'wrong_amount_of_cash_received', 'wrong_exchange_rate_for_cash_withdrawal'], id=None)}

In [9]:
dataset["train"].features["label"]

ClassLabel(names=['activate_my_card', 'age_limit', 'apple_pay_or_google_pay', 'atm_support', 'automatic_top_up', 'balance_not_updated_after_bank_transfer', 'balance_not_updated_after_cheque_or_cash_deposit', 'beneficiary_not_allowed', 'cancel_transfer', 'card_about_to_expire', 'card_acceptance', 'card_arrival', 'card_delivery_estimate', 'card_linking', 'card_not_working', 'card_payment_fee_charged', 'card_payment_not_recognised', 'card_payment_wrong_exchange_rate', 'card_swallowed', 'cash_withdrawal_charge', 'cash_withdrawal_not_recognised', 'change_pin', 'compromised_card', 'contactless_not_working', 'country_support', 'declined_card_payment', 'declined_cash_withdrawal', 'declined_transfer', 'direct_debit_payment_not_recognised', 'disposable_card_limits', 'edit_personal_details', 'exchange_charge', 'exchange_rate', 'exchange_via_app', 'extra_charge_on_statement', 'failed_transfer', 'fiat_currency_support', 'get_disposable_virtual_card', 'get_physical_card', 'getting_spare_card', 'getting_virtual_card', 'lost_or_stolen_card', 'lost_or_stolen_phone', 'order_physical_card', 'passcode_forgotten', 'pending_card_payment', 'pending_cash_withdrawal', 'pending_top_up', 'pending_transfer', 'pin_blocked', 'receiving_money', 'Refund_not_showing_up', 'request_refund', 'reverted_card_payment?', 'supported_cards_and_currencies', 'terminate_account', 'top_up_by_bank_transfer_charge', 'top_up_by_card_charge', 'top_up_by_cash_or_cheque', 'top_up_failed', 'top_up_limits', 'top_up_reverted', 'topping_up_by_card', 'transaction_charged_twice', 'transfer_fee_charged', 'transfer_into_account', 'transfer_not_received_by_recipient', 'transfer_timing', 'unable_to_verify_identity', 'verify_my_identity', 'verify_source_of_funds', 'verify_top_up', 'virtual_card_not_working', 'visa_or_mastercard', 'why_verify_identity', 'wrong_amount_of_cash_received', 'wrong_exchange_rate_for_cash_withdrawal'], id=None)

In [10]:
len(dataset["train"])

10003

In [11]:
len(dataset["test"])

3080

In [12]:
dataset["train"][:10]

{'text': ['I am still waiting on my card?',
  "What can I do if my card still hasn't arrived after 2 weeks?",
  'I have been waiting over a week. Is the card still coming?',
  'Can I track my card while it is in the process of delivery?',
  'How do I know if I will get my card, or if it is lost?',
  'When did you send me my new card?',
  'Do you have info about the card on delivery?',
  'What do I do if I still have not received my new card?',
  'Does the package with my card have tracking?',
  "I ordered my card but it still isn't here"],
 'label': [11, 11, 11, 11, 11, 11, 11, 11, 11, 11]}

In [13]:
df = dataset["train"].to_pandas()
df.head()

                                                text  label
0                     I am still waiting on my card?     11
1  What can I do if my card still hasn't arrived ...     11
2  I have been waiting over a week. Is the card s...     11
3  Can I track my card while it is in the process...     11
4  How do I know if I will get my card, or if it ...     11

In [14]:
df.sample(10)

                                                   text  label
7591  How can I move money from my account at a diff...     65
6252  I can't get my card out of the ATM, what shoul...     18
8367  I withdrew cash abroad and the exchange rate a...     76
732              I was overcharged an additional pound.     34
2366           my cash balance less than what I thought     75
3788        Why do you require identification documents     74
3299        Can you tell me why my top-up was canceled?     61
3037                            how to get virtual card     40
7422  If my salary is in GBP, do I need to do someth...     50
6637  I've made a transfer, how long until the money...     67

In [15]:
len(dataset["train"].features["label"].names)

77

In [16]:
dataset["train"].features["label"].names

['activate_my_card',
 'age_limit',
 'apple_pay_or_google_pay',
 'atm_support',
 'automatic_top_up',
 'balance_not_updated_after_bank_transfer',
 'balance_not_updated_after_cheque_or_cash_deposit',
 'beneficiary_not_allowed',
 'cancel_transfer',
 'card_about_to_expire',
 'card_acceptance',
 'card_arrival',
 'card_delivery_estimate',
 'card_linking',
 'card_not_working',
 'card_payment_fee_charged',
 'card_payment_not_recognised',
 'card_payment_wrong_exchange_rate',
 'card_swallowed',
 'cash_withdrawal_charge',
 'cash_withdrawal_not_recognised',
 'change_pin',
 'compromised_card',
 'contactless_not_working',
 'country_support',
 'declined_card_payment',
 'declined_cash_withdrawal',
 'declined_transfer',
 'direct_debit_payment_not_recognised',
 'disposable_card_limits',
 'edit_personal_details',
 'exchange_charge',
 'exchange_rate',
 'exchange_via_app',
 'extra_charge_on_statement',
 'failed_transfer',
 'fiat_currency_support',
 'get_disposable_virtual_card',
 'get_physical_card',
 'getting_spare_card',
 'getting_virtual_card',
 'lost_or_stolen_card',
 'lost_or_stolen_phone',
 'order_physical_card',
 'passcode_forgotten',
 'pending_card_payment',
 'pending_cash_withdrawal',
 'pending_top_up',
 'pending_transfer',
 'pin_blocked',
 'receiving_money',
 'Refund_not_showing_up',
 'request_refund',
 'reverted_card_payment?',
 'supported_cards_and_currencies',
 'terminate_account',
 'top_up_by_bank_transfer_charge',
 'top_up_by_card_charge',
 'top_up_by_cash_or_cheque',
 'top_up_failed',
 'top_up_limits',
 'top_up_reverted',
 'topping_up_by_card',
 'transaction_charged_twice',
 'transfer_fee_charged',
 'transfer_into_account',
 'transfer_not_received_by_recipient',
 'transfer_timing',
 'unable_to_verify_identity',
 'verify_my_identity',
 'verify_source_of_funds',
 'verify_top_up',
 'virtual_card_not_working',
 'visa_or_mastercard',
 'why_verify_identity',
 'wrong_amount_of_cash_received',
 'wrong_exchange_rate_for_cash_withdrawal']